### ISSUE TITLE
Missing New Monsters (and maybe new equipments)

### ISSUE THREAD

**Issue by Syndaya** [yquake2/xatrix#10]
I suppose (more test needed) that all new contents are missing in the last version (2.05).

On the first map the enemy count is 0/14 instead of 0/38 (in Easy Mode), the only 2 monsters present in the first part of the map are 2 Grunt at the end.

Sorry for my English, I will do more test when possible.

OP: Windows 7 64 bit
Tested on: GOG Edition and original CD-ROM release (1998 Edition)

**Comment by Yamagi** [comment]
Hello,
I'm unable to reproduce this with our official Windows binaries. It looks like the game is falling back to the baseq2 game.dll for some reason. Are you sure that xatrix\game.dll exists and it's the correct DLL?

**Comment by Syndaya** [comment]
Yes, I check many times, I download Yamagi Quake II Client 7.00 from here:

    https://deponie.yamagi.org/quake2/windows/quake2-7.00.zip

and follow the instructions in the Readme file (installing the patch v3.20, deleting unnecessary files etc. etc.)... The info of game.dll are these:

Filesize: 2.341 KB
Release date: 09/06/2017 18.04

I tried with other dlls and no problems at all (well, some crazy monster's jumps or "slippery" terrains but they are present in different way in all versions, so it's ok):

- gamex86.dll from CD-ROM installation + Patch 3.20
- gamex86.dll from CD-ROM installation + Patch 3.24
- gamex86.dll from GOG.com installation
- game.dll from Yamagi Client 6.00

For now I did not found problems with the other 2 game.dll (baseq2 and rogue)...

I use an Italian version of Windows 7 64 bit, maybe there are some language differences in the system files the may cause the problem or interfere in some way?

**Comment by Yamagi** [comment]
Okay. That's strange. Can you confirm that the xatrix\game.dll is 2.396.411 bytes long (Right click on the file -> Properties) and post a copy of Documents\YamagiQ2\xatrix\qconsole.log? That may help to debug this.

**Comment by Syndaya** [comment]
Ok. the game.dll is exactly 2.396.411 byte long. I used a fresh GOG.com Installation for test with YQC 7.00 + OGG Audio Tracks (the GOG version are non the best ones).

As supposed, it use the baseq2 models instead of the xatrix one. The log:

[qconsole.log.txt](https://github.com/yquake2/xatrix/files/1078103/qconsole.log.txt)

**Comment by Syndaya** [comment]
I made another fresh Installation (ah, GOG.com is pratic to reinstall in few seconds), this time I use YQC 6.00 without OGG Audio Tracks. I put on for comparation, it work fine.

[qconsole.log.txt](https://github.com/yquake2/xatrix/files/1078138/qconsole.log.txt)

**Comment by DanielGibson** [comment]
How do you start the game with the addon? What commandline arguments do you use?

**Comment by Syndaya** [comment]
Well, the CD-ROM Edition with a bat with this command line:

    quake2.exe +set game xatrix

The GOG.com Edition instead comes with a beautiful configurable Lancher where u can choose what game/mod start.

![image1](https://user-images.githubusercontent.com/29441971/27198899-68ef68fe-5214-11e7-9110-dc006bfe967d.jpg)

The entry in the .ini file relative to Xatrix is this:

    [Reckoning]
    Name=The Reckoning
    Exe={app}/quake2.exe
    paramRUN=+set game xatrix
    paramSAFE=+set game xatrix +set vid_ref soft +set vid_fullscreen 0 +set sw_mode 0 +set s_wavonly 1
    paramDC=+set game xatrix +set deathmatch 1 +set dedicated 1

With every gameXXX.dll EXCEPT the one of YQC 7.00 downloaded some days ago the game runs well (I tried the 1st full mission for the moment), so the Lancher is regular, I presume.

I don't know what other tests do atm, we accept suggestions ^^'

**Comment by DanielGibson** [comment]
So what happens if you use all the stuff from 7.00, but the xatrix/game.dll from 6.00?

**Comment by Syndaya** [comment]
I'm actually using atm YQC 7.00 with Xatrix dll from v6.00 for playing. The monsters are present on 1st map (The Swamps) and the maps I've played appear to be regular (4 for now).

The only strange thing, but I presume don't depend from YQC, is that Gekks body on waters continue to move and eventually resurrect some times...

**Comment by Yamagi** [comment]
That's very strange... I thought that we maybe had another bug in Quake2s crappy path logic. The search pathes were somewhat buggy in the original client. Fixing the bugs would break mods, so we need to retain them while supporting new features. That's not very nice. But all this can't be the case if a 6.00 DLL is working with a 7.00 client.

Your log says: "Game is baseq2 built on Jun  9 2017."  So it's loading the wrong DLL. The question is why.

I have two ideas:

* Can you upload the not working xatrix/game.dll from 7.00 somewhere or send it me by mail to yamagi@yamagi.org?
* Can you have a look that there's no game.dll in the YamagiQ2 folder in your Documents?

**Comment by Yamagi** [comment]
Okay, forget it. I found it. It's an issue with our new build system. On some platforms the game.dll is missing a dependent DLL and falls back to baseq2\game.dll. I know how to fix that but it'll have to wait until I'm at home.

**Comment by Yamagi** [comment]
Here's a new set of binaries: https://deponie.yamagi.org/quake2/misc/quake2_mingw_fix.zip They shpuld fix the problem. Can you tell me that it's really the case?

**Comment by Syndaya** [comment]
Avast Antivirus has find something on Quake2.exe and has sended the file on his central for further control, so no control for now on the new package.

Anyway, I put on the previus YQC 7.00 with the new 4 .dll and they have worked regurarly. The Xatrix count is correct on the first map (0/38), and the log appear to be ok.

The only thing I found is in the rogue log, I report here just for conoscence:

[0.0.0.0]:0: client_connect
------- server initialization ------
69 entities inhibited.
5 teams repaired
8 teams with 22 entities.
G_PickTarget: target t353 not found
monster_flyer can't find target t353 at (-816 -736 256)
------------------------------------

When AVAST will decide to permit me to use the new .exe I will do more test (disable it don't resolve)... You apologize for the wait, but I was hoping AVAST would quickly see the false positives, allowing me to do a "full" test.

**Comment by Syndaya** [comment]
Ok, AVAST is quiete now, I played 4 maps of Xatrix, all regular ^_^

**Comment by Yamagi** [comment]
Nice that it works. I'll release a new version 7.01 with is and some other small bugfixes early next week. Thank you for the report and your help with fixing this.

G_PickTarget: target t353 not found: This is harmless. It's just a small nit in the map. Both addons have several of these. There's no need to fix them since the maps work fine as they are. But maybe we could hide the messages.

Regarding Avast: It's likely that the malware scanner triggered because you changed quake2.exe too often. I have experienced the same problem with several scanners (Windows Defender, Avira, Sophos) while testing. After the third or fourth change the binary is classified as suspicious.
