### ISSUE TITLE
Use of non-portable system strcasecmp rather than portable version 

### ISSUE THREAD

**Issue by ajbonner** [yquake2/xatrix#11]
This is not so much an issue for building on unix/cygwin, but I noticed this when compiling rogue/xatrix on win32 under visual studio.

The code compiles file except the linker obviously complains about Q_stricmp, because rather than delegating to the portable Q_strcasecmp it's using the libc strcasecmp.

https://github.com/yquake2/xatrix/blob/master/src/shared/shared.c#L1017

The 'fix' as such is to just replace strcasecmp with a call to Q_strcasecmp or to avoid any additional indirection, straight to Q_strncasecmp.

The same 'issue' exists in rogue.

*Edit* Just wanted to add my thanks to all of you for maintaining this codebase. I drop in and out of playing around with it for fun and it's fantastic to have this code just work for the most part and allow novices to tinker with it! Thank you all again!

**Comment by Yamagi** [comment]
Hi,
I've just pushed the change to all 3 addons. Thank you! :)

**Comment by ajbonner** [comment]
Hey, that's great, thank you so much again 👍
