### ISSUE TITLE
Cinematic openings, demos and the ending don't play

### ISSUE THREAD

**Issue by NeonKnightOA** [yquake2/xatrix#12]
Using Yamagi Quake II ver. 7.30 plus Xatrix ver. 2.05 under Windows 7.

Opening the game through a shortcut (with +game xatrix) has the game go directly to the console. It doesn't play the opening logos or the demos.

Additionally, after finishing an SP run, the ending cinematic is cut short, right before the ship escapes from the collapsing base. If I want to fully see it, I have to write "map xout.cin".

**Comment by Yamagi** [comment]
> Opening the game through a shortcut (with +game xatrix) has the game go directly to the console. It doesn't play the opening logos or the demos.

Hmm... I can't reproduce that. Have you any non ASCII characters in the path to the game data or your documents dir? In that case it may be another UTF-8 problem.
