### ISSUE TITLE
Resolve issues found by PVS

### ISSUE THREAD

**Issue by demoth** [yquake2/xatrix#17]
Hi

I have run pvs against the code. Attaching the report

https://docs.google.com/spreadsheets/d/1Cdhvjp7AtAlOfyxOLlTFGOX2gO8Rhf2cbx77A-MPgIE/edit?usp=sharing

**Comment by Yamagi** [comment]
I just merged the PR. So this one is closed, too. Now only yquake2 itself is still missing.
