### ISSUE TITLE
The Warehouse - platforms not moving

### ISSUE THREAD

**Issue by whizse** [yquake2/xatrix#2]
I'm playing through The Reckoning (using Yamagi 5.11 and Xatrix 2.01) and I think I have found a bug.

In the "The Warehouse" level the platforms that should be moving sideways and later up and down are not activated, so it's impossible to progress (without cheating), however sound effects for them moving are being played.

I have attached a screenshot of the area.
![screenshot from 2013-10-08 11 51 53](https://f.cloud.github.com/assets/5636822/1287855/4710778a-3000-11e3-87c1-cbbc53bbf04a.png)

**Comment by DanielGibson** [comment]
should be fixed
