### ISSUE TITLE
[Original bug] Beta class iron maidens lose homing rockets when pain skin appears

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/xatrix#20]
To reproduce:
1. Go to map refinery
2. Let the first iron maiden in the level see you and attack you
3. Notice that she fires homing rockets
4. Hurt her until her pain skin appears
5. Let her attack again
6. Now notice that it is just a normal non-homing rocket

This happens because the programmer uses s.skinnum to choose between firing rockets or homing rockets. Beta class skin is 3, but both types of iron maidens use skin 1 for pain skin, so as soon as the pain skin is set, the check for homing rockets will evaluate to false and regular rocket is fired by the beta class iron maiden.

There is the tiny chance that this is actually intentional, but given how the code is written it seems very much like an oversight that was not intended to be there. Plus, no other monster in the entire Quake 2 line-up behaves like this.

If you want I can provide a pull request with a fixup.

**Comment by Yamagi** [comment]
I see the problem. If you already have a fix, I'd merge it.
