### ISSUE TITLE
Bug: msys.bat + missing lines in Makefile

### ISSUE THREAD

**Issue by Player701** [yquake2/xatrix#3]
The first part of the issue applies to all games, the second part applies to "xatrix" and "rogue".

I downloaded the build environment by the link provided in the compilation instructions (http://deponie.yamagi.org/quake2/windows/build/quake2_buildenv_20140508.zip). You recommended to start the 32-bit build environment, so I clicked on MSYS32.lnk, and a cmd.exe window opened. But there was no text or input prompt there, so I thought it prepares the environment (unpacks files maybe?) and then I started cloning the GitHub repositories of "yquake2", "xatrix" and "rogue". Well, when I finished doing that, I noticed that the CPU usage went up high. I opened Task Manager and... there were like 2000+ copies of cmd.exe running! It seemed that the .bat file linked to by MSYS32.lnk went into an inifinite recursion, each new copy starting and calling another copy of itself. Fortunately I was able to kill all the cmd.exe processes, and then I looked into the .bat file to find out why it happened. Seems that the problem was in these lines:

```bat
rem Hopefully a temporary workaround for getting MSYS shell to run on x64
rem (WoW64 cmd prompt sets PROCESSOR_ARCHITECTURE to x86)
if not "x%PROCESSOR_ARCHITECTURE%" == "xAMD64" goto _NotX64
set COMSPEC=%WINDIR%\SysWOW64\cmd.exe
%COMSPEC% /c %0 %1 %2 %3 %4 %5 %6 %7 %8 %9
goto EOF
```

Looks like PROCESSOR_ARCHITECTURE is always reported the same, regardless of the command prompt opened (normal cmd.exe in System32 or the one in SysWOW64). I think this behavior is correct (why the hell should processor architecture depend on the command prompt?). Maybe it was fixed with some Windows updates. So this "temporary workaround" in the bat file is now failing, because Wow64 cmd propmpt does not set PROCESSOR_ARCHITECTURE to x86, at least on my PC (I have Windows 7 64-bit).

This problem was solved by commenting out these lines. The _NotX64 label was right after these lines, so after the "fix" the build environment started.

Now another issue: Makefiles for "xatrix" and "rogue" lack these lines, which are critical for building on Windows. They are present in "yquake2" makefile nevertheless:

```makefile
# On Windows / MinGW $(CC) is
# undefined by default.
ifeq ($(OSTYPE),Windows)
CC := gcc
endif
```

Luckily for me, after adding them everything compiled flawlessly. You did a very good job preparing the environment so people don't have to download countless dependencies and configure everything manually. Well done, thanks :)

**Comment by DanielGibson** [comment]
I added the `CC := gcc` part, for me it works now with our build environment on Win7 64bit.
Thanks for reporting :-)
