### ISSUE TITLE
Bug: Fan in the Warehouse level, ungettable secret

### ISSUE THREAD

**Issue by Player701** [yquake2/xatrix#4]
This is not a game-breaking bug, but it prevents you from getting one of the two secrets in the level. I'll try to describe it as best as I can...

There is an area in the level, where there is a working fan and a some kind of power device which you are supposed to shoot, thus disabling the fan, and then you have to fall down between the fan blades to progress further into the level. But there's also a secret related to this fan. If you don't shoot the power device, you can step under the fan, and its airflow should push you up to the ceiling. You must use the fan's wind-force to navigate yourself into a small passage above the fan, and this is where the secret is located. Why did I say "should push you"? Well, because in YQuake2 this does not work. This fan acts very strangely, I can't exactly describe how, but it is like the air force exists only over the blades of the fan, and doesn't exist in the area over the gaps between the blades. Depending on the part of the fan (gap / blade) ending up below you when you step under it, you may either be almost instantly thrown in the water below the fan - for me it was so fast that I couldn't see myself falling down - or you may end up finding yourself hitting the ceiling like 5 or 10 times with insane force, and then either ending your life by being sliced by fan blades, or hitting the blades' surfaces with an acceleration so high that it instantly deals massive damage enough for the health meter to show "-99" health. Somehow you may survive, however, and in this case you will also end up in the water below the fan. But it is of course evident that the secret becomes nigh to impossible to get with this fan demonstrating such a bizarre behavior. I was finally able to get the secret by rocket jumping, but it is clearly not the way it's supposed to be taken.

When playing the original game a couple years ago, I don't recall having encountered this bug (I can't test the original game now because I started to run into problems running it after upgrading my system - this is how I began searching for a port in the first place). I also downloaded KMQuake2 to check if the bug also appears there. And I found out that this fan acts normally in KMQuake2. So it definitely looks like a bug in YQuake2, or perhaps a fixable map error (if I forgot about the bug in the original game and it was present there). Could you fix this so the secret becomes gettable by the way it was supposed to be got?

**Comment by DanielGibson** [comment]
We're working on it, see https://github.com/yquake2/yquake2/issues/71

**Comment by DanielGibson** [comment]
Should be fixed now (in git at least, we'll provide updated binaries later), thanks for reporting and sorry it took so long :-)

**Comment by Yamagi** [comment]
And the binaries can be found here: http://deponie.yamagi.org/quake2/windows/quake2-5.31pre1.zip
