### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by BielBdeLuna** [yquake2/xatrix#5]
~/.quake2/xatrixsrc/xatrix$ make
===> Building game.so
make release/game.so
make[1]: Entering directory '/home/biel/.quake2/xatrixsrc/xatrix'
===> CC src/g_ai.c
===> CC src/g_chase.c
===> CC src/g_cmds.c
===> CC src/g_combat.c
===> CC src/g_func.c
===> CC src/g_items.c
===> CC src/g_main.c
===> CC src/g_misc.c
===> CC src/g_monster.c
===> CC src/g_phys.c
===> CC src/g_spawn.c
===> CC src/g_svcmds.c
===> CC src/g_target.c
===> CC src/g_trigger.c
===> CC src/g_turret.c
===> CC src/g_utils.c
===> CC src/g_weapon.c
===> CC src/monster/berserker/berserker.c
===> CC src/monster/boss2/boss2.c
===> CC src/monster/boss3/boss3.c
===> CC src/monster/boss3/boss31.c
===> CC src/monster/boss3/boss32.c
===> CC src/monster/boss5/boss5.c
===> CC src/monster/brain/brain.c
===> CC src/monster/chick/chick.c
===> CC src/monster/fixbot/fixbot.c
===> CC src/monster/flipper/flipper.c
===> CC src/monster/float/float.c
===> CC src/monster/flyer/flyer.c
===> CC src/monster/gekk/gekk.c
===> CC src/monster/gladiator/gladb.c
===> CC src/monster/gladiator/gladiator.c
===> CC src/monster/gunner/gunner.c
===> CC src/monster/hover/hover.c
===> CC src/monster/infantry/infantry.c
===> CC src/monster/insane/insane.c
===> CC src/monster/medic/medic.c
===> CC src/monster/misc/move.c
===> CC src/monster/mutant/mutant.c
===> CC src/monster/parasite/parasite.c
===> CC src/monster/soldier/soldier.c
===> CC src/monster/supertank/supertank.c
===> CC src/monster/tank/tank.c
===> CC src/player/client.c
===> CC src/player/hud.c
===> CC src/player/trail.c
===> CC src/player/view.c
===> CC src/player/weapon.c
===> CC src/savegame/savegame.c
src/savegame/savegame.c: In function ‘ReadField’:
src/savegame/savegame.c:577:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(*(char **)p, len, 1, f);
     ^
src/savegame/savegame.c:635:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread (funcStr, len, 1, f);
     ^
src/savegame/savegame.c:659:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread (funcStr, len, 1, f);
     ^
src/savegame/savegame.c: In function ‘ReadClient’:
src/savegame/savegame.c:711:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(client, sizeof(*client), 1, f);
  ^
src/savegame/savegame.c: In function ‘ReadGame’:
src/savegame/savegame.c:806:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(str_ver, sizeof(str_ver), 1, f);
  ^
src/savegame/savegame.c:807:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(str_game, sizeof(str_game), 1, f);
  ^
src/savegame/savegame.c:808:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(str_os, sizeof(str_os), 1, f);
  ^
src/savegame/savegame.c:809:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(str_arch, sizeof(str_arch), 1, f);
  ^
src/savegame/savegame.c:836:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&game, sizeof(game), 1, f);
  ^
src/savegame/savegame.c: In function ‘ReadEdict’:
src/savegame/savegame.c:968:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(ent, sizeof(*ent), 1, f);
  ^
src/savegame/savegame.c: In function ‘ReadLevelLocals’:
src/savegame/savegame.c:987:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&level, sizeof(level), 1, f);
  ^
src/savegame/savegame.c: In function ‘ReadLevel’:
src/savegame/savegame.c:1028:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&i, sizeof(i), 1, f);
  ^
===> CC src/shared/flash.c
===> CC src/shared/rand.c
===> CC src/shared/shared.c
===> LD release/game.so
collect2: error: ld returned 1 exit status
Makefile:218: recipe for target 'release/game.so' failed
make[1]: *** [release/game.so] Error 1
make[1]: Leaving directory '/home/biel/.quake2/xatrixsrc/xatrix'
Makefile:127: recipe for target 'xatrix' failed
make: *** [xatrix] Error 2

**Comment by Jarvik7** [comment]
Compiles fine for me...

**Comment by BielBdeLuna** [comment]
I'm sorry to have bothered you i think the error was due no space on my hdd rather than an error from coding, it compiled fine after.
