### ISSUE TITLE
Swamps: can't get adrenaline (can't fit to it's location)

### ISSUE THREAD

**Issue by thesourcehim** [yquake2/xatrix#50]
In the the Swamps there's a secret adrenaline in the small pool of water near the end (first visit) of the map. The problem is I can't reach it, there seem to be not enough space for player to fit, or the adrenaline is placed lower than it should be somehow.

**Comment by BjossiAlfreds** [comment]
I just tested myself and can confirm this.

Using listentities, the adrenaline's origin looks very strange, like it was moved algorithmically after being spawned. In the original dll its final location after droptofloor() is -623 398 72, while it is -604.55 410.65 15 in YQ2 which is very odd. That big difference in vertical position may be why it is unreachable.

I tried running my own dll using YQ2 and that works fine, so this has something to do with game.dll I would assume.

**Comment by NeonKnightOA** [comment]
So, what could be the function to check? Maybe I can create a PR and submit it.

**Comment by BjossiAlfreds** [comment]
I did more digging, this is happening inside SV_Physics_Toss() in g_phys.c. The adrenaline item spends quite a few frames sliding around before falling into its final position. However in the original game this happens right away - it doesn't move at all. So there is something different in the code, or possibly a side-effect of compiler options that have to do with optimizations or floating point precision.

**Comment by BjossiAlfreds** [comment]
I figured it out. In SV_PushEntity() in g_phys.c, at lines 514 - 517 is new YQ2 code that when commented out fixes the problem. I guess it just so happens that in this case, the adjustments lead to the entity getting moved around and eventually falls into an inaccessible space.

I'm assuming Yamagi wouldn't want to remove the code as it prevents other issues with entities rendering black, so perhaps a map hack or a fixed .ent file would do the trick?

**Comment by NeonKnightOA** [comment]
Indeed, a map hack via code may be the best solution.

**Comment by Yamagi** [comment]
A map fix would be one option. The problem is, that we found the first place were the lighting fix breaks game logic. There might be more of them, especially in rather crude custom maps... @DanielGibson and I will ponder about it. If we can come up with another fix for the lighting problem, everything's okay. Otherwise we'll add a map fix.

**Comment by thesourcehim** [comment]
I tested mentioned commit (yquake2, debris_fix branch), but the problem persists.

**Comment by Yamagi** [comment]
I've pushed the fix to all addons.
