### ISSUE TITLE
Incorrect blue laser sound in The Reckoning

### ISSUE THREAD

**Issue by richterdeveloper** [yquake2/xatrix#51]
Hello!! The sound of the soldier's blue lasers is dissorted or is wrong. If you play the original game (it's payable in Windows 10) the sound is diferent. You can hear that in the first demo sequence of the game. 

Thanks!!

**Comment by BjossiAlfreds** [comment]
I compared both the original game and YQ2 and could not tell the difference. Do youy any chance have s_doppler set to 1? Make sure that is set to 0 as it really messes up the game audio.

**Comment by richterdeveloper** [comment]
> I compared both the original game and YQ2 and could not tell the difference. Do youy any chance have s_doppler set to 1? Make sure that is set to 0 as it really messes up the game audio.

Yes, s_doppler cause distortion audio. Set s_doppler to 0 is the solution. Thanks!!

**Comment by Yamagi** [comment]
Maybe we should set s_doppler to 0 as default?

**Comment by BjossiAlfreds** [comment]
I would say yes, personally, for the sake of keeping the game sounding like what people are used to. It is also not a good mimic of real world doppler effects so it doesn't sound intuitive.
