### ISSUE TITLE
Ion ripper and gunner ducking

### ISSUE THREAD

**Issue by CyberKiller40** [yquake2/xatrix#57]
I recently played through The Reckoning using the current release of yamagiq2 and I found that whenever I'm shooting with the ion ripper and a gunner ducks from my shots, the shots go through his ducked torso without damaging (no blood is shown). This seems to be a bug, though I have no idea how that worked in the base game. It seems only gunners are affected by this (the only sure way to hit them is by shooting the legs).

**Comment by BjossiAlfreds** [comment]
The game's ducking system isn't exactly fancy. All monsters that duck down have a 32 unit lower hitbox while ducked, regardless of how far down they duck visually. The gunner's hitbox is 56 units tall normally so when he ducks down his hitbox is less than half the normal height (24). It may be that he doesn't visually duck down as much as other monsters so his model sticks more out of the box than other monsters do.

I don't really know why the ion ripper bolts would be more subject to this than other projectiles. Perhaps they are slower and that gives the gunner more time to finish his ducking down move and lower his hitbox before the projectile reaches him?

Just in case I did take a quick look at the gunner's ducking code and the ion ripper's projectile firing code and saw nothing out of the ordinary. So I'd just call this Quake 2's primitive collision detection and ducking systems at work. While it would certainly be possible to tweak hitbox sizes and even do so on a per-monsterframe basis to be extra fancy, but I don't think that kind of stuff is in the scope of YQ2 and would take a lot of tedious incremental changes and testing.

**Comment by CyberKiller40** [comment]
Alright, I understand. Thank you for taking the time to check this.
