### ISSUE TITLE
Brains does not use beam attack

### ISSUE THREAD

**Issue by MyLittleRobo** [yquake2/xatrix#6]
I've never finished original Reckoning, so yquake2 version was the first for me. In some gameplay video I saw Brains are able to use laser beam attack, but I'd never seen this in the game by myself. I even made a separate map with monster_brain and they act like regular brains from Quake 2. 
I took game resource from Steam version if it matters.

**Comment by Yamagi** [comment]
The laser beams are working, but it's very unlikely to trigger them. We use the same propability as the original game.dll.
