### ISSUE TITLE
Laser guard death animation

### ISSUE THREAD

**Issue by drakonorodny** [yquake2/xatrix#68]
Hi again,
If the laser guard goes into the 'last stand' animation, he fires off a couple of empty shots before dying. This is probably because the laser beam is implemented differently in the code than the projectile/hitscan weapons that the other guard types have (though I can't say for sure).

The animation is controlled by the following `if` statement in the function `soldierh_die`:

`if (n == 0)`
`	{`
`		self->monsterinfo.currentmove = &soldierh_move_death1;`
`	}`

My suggestion would be to add an extra condition to play a different death animation if it is a laser guard (`self->s.skinnum >= 4`).

**Comment by Yamagi** [comment]
Can you send a pull request?

**Comment by BjossiAlfreds** [comment]
Just a minor nitpick - that change would give n == 1 a pretty big bias over the n > 1 choices. I'd instead change how n is calculated, example:

n = (self->s.skinnum < 4) ? (rand() % 5) : (1 + (rand() % 4));
