### ISSUE TITLE
R_DrawAliasModel "no such oldframe" messages on weapon switch while firing using DualFire Damage

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/xatrix#7]
When DualFire Damage is active, firing a weapon and then switching weapons will often result in R_DrawAliasModel producing messages about missing frames:

<code>
R_DrawAliasModel models/weapons/v_handgr/tris.md2: no such oldframe 64
R_DrawAliasModel models/weapons/v_handgr/tris.md2: no such oldframe 64
R_DrawAliasModel models/weapons/v_handgr/tris.md2: no such oldframe 64
R_DrawAliasModel models/weapons/v_handgr/tris.md2: no such oldframe 64
R_DrawAliasModel models/weapons/v_handgr/tris.md2: no such oldframe 64
R_DrawAliasModel models/weapons/v_handgr/tris.md2: no such oldframe 64
R_DrawAliasModel models/weapons/v_hyperb/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_hyperb/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_hyperb/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_hyperb/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_hyperb/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_shotg/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_shotg/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_shotg/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_shotg/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_shotg/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_shotg/tris.md2: no such oldframe 54
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
R_DrawAliasModel models/weapons/v_boomer/tris.md2: no such oldframe 53
</code>

**Comment by DanielGibson** [comment]
those warnings are harmless; I pushed a change to the quake2 client to silence them (they're developer messages instead of normal messages now and thus aren't usually shown)
