### ISSUE TITLE
Reckoning Crash on Start Up 

### ISSUE THREAD

**Issue by Vaedzak** [yquake2/xatrix#72]
Hi there! Fist and foremost thank you so much for Yagami, it was an amazing way to experience Quake 2. That being said when I went to play The Reckoning I found that it simply crashed on start up. I followed all instructions in the read me, and the game will allow me to go to the main menu, but as soon as I attempt to start a new game it simply crashes. 

Tried a fresh install, that didn't work either. Normally I prefer to solve my own problems but I'm at a loss here. Any advice or further instruction would be great, thanks again for creating Yagami!

**Comment by Yamagi** [comment]
I cannot reproduce this. I guess it's under Windows? Can you send us the log file, found in C:\Users\$username\Documents\YamagiQ2\stdout.txt?
