### ISSUE TITLE
Coop: xsewer1.bsp hatches switching progress breaker.

### ISSUE THREAD

**Issue by maraakate** [yquake2/xatrix#9]
In coop on xsewer1.bsp when you open the first hatch, then journey on to open the second one and die before you can get a chance to hit the final switch you won't be able to re-enter the area to continue on requiring a reset of the map.

The following code I added to q2dos's coop mod fixes this issue:
https://bitbucket.org/neozeed/q2dos/commits/dda8a17ec2883ccfb7688d5bd8410a6546d0a2f0

**Comment by Yamagi** [comment]
I've just pushed the fix. Thank you!
