### ISSUE TITLE
Monster footsteps not working

### ISSUE THREAD

**Issue by mooreye** [yquake2/xatrix#91]
I have `footsteps.pkz` downloaded and option `set g_monsterfootsteps "1"` enabled.
For base Quake 2 it works fine, but for xatrix and rogue I hear no footsteps of any monsters.

**Comment by BjossiAlfreds** [comment]
Unfortunately the contributor who did that feature only did it for baseq2. Could try nudge them about xatrix/rogue/zaero, otherwise someone else will have to do the porting.

**Comment by Yamagi** [comment]
The footsteps were ported from SkacikPLs Q2RTS fork: https://github.com/SkacikPL/Q2RTX They didn't implement them for the addons. It shouldn't be too hard, however Q2 itself is licensed under GPL and the addons under the crappy SDK license. If someone wants to implement footsteps for the addons they need to ask SkacikPL if the license change is okay.

**Comment by Yamagi** [comment]
Footsteps are now implemented.
