### ISSUE TITLE
Relicense under GPL?

### ISSUE THREAD

**Issue by SirYodaJedi** [yquake2/xatrix#93]
Tangentially related to yquake2/yquake2remaster#3 and yquake2/rogue#113

With the Kex port of Quake II, Id has also relicensed the original game code for the two expansions under GPL 2.0, in addition to the modified rerelease game code ([id-Software/quake2-rerelease-dll](https://github.com/id-Software/quake2-rerelease-dll)). I'm not sure how doable this would be for yq2's forks (given the multiple authors), but I figured I'd bring it up, since it could make cross-repo license shenanigans less convoluted.

**Comment by Yamagi** [comment]
I have opened a new issue under #96.
