### ISSUE TITLE
Relicense Yamagi Quake II Xatrix (The Reckoning) under GPL2

### ISSUE THREAD

**Issue by Yamagi** [yquake2/xatrix#96]
Hi,

until now the Quake II addons were licensed under the id Software SDK license, which isn't really an open source license. It causes problems with distributing the addons as part of the Yamagi Quake II project, both we and most downstream projects like Linux distributions are forced  to keep the main project and the addons seperated. And it makes merging code from and to the GPL2 licensed Yamagi Quake II hard.

With the Quake II Enhanced Edition id Software generously relicensed the unaltered addons source code under GPL2: https://github.com/id-Software/quake2-rerelease-dll This allows us to relicense our bugfixed versions of the addons. To do
that we need the okay from all past contributors.

You receive this message / heads up / tag because you have contributed at least one commit to the Yamagi Quake II Xatrix project: https://github.com/yquake2/xatrix Please give us a short answer that you are okay with relicensing the project from the id Software SDK license to GPL2.

List of contributors:

* [x] Andrey Nazarov - @skullernet
* [x] Angus Freudenberg - @afreuden
* [x] @BjossiAlfreds
* [x] @DanielGibson
* [x] David Carlier - @devnexen
* [x] Denis Pauk - @0lvin
* [x] @De-Seppe 
* [ ] @Dremor8484
* [x] Jaime Moreira - @protocultor
* [x] Joshua Scoggins - @DrItanium
* [x] Mitchell Richters - @mjr4077au
* [x] @NeonKnightOA
* [x] Scott - @Pickle
* [x] svdijk - @svdijk
* [x] Yamagi

**Comment by Yamagi** [comment]
* I give my okay.
* @DanielGibson gave me his okay.
* @BjossiAlfreds gave is okay in https://github.com/yquake2/rogue/pull/113
* @0lvin gave his okay in https://github.com/yquake2/rogue/pull/113
* @protocultor gave his okay in https://github.com/yquake2/rogue/pull/113

**Comment by Yamagi** [comment]
Of course you can give your okay here for both addons.

**Comment by Yamagi** [comment]
@devnexen gave his okay in https://github.com/yquake2/rogue/issues/122#issuecomment-1741811878

**Comment by Yamagi** [comment]
@DrItanium gave his okay in https://github.com/yquake2/rogue/issues/122#issuecomment-1741818222

**Comment by Yamagi** [comment]
@skullernet gave his okay in https://github.com/yquake2/rogue/issues/122#issuecomment-1741843330

**Comment by Yamagi** [comment]
@mjr4077au gave his okay in https://github.com/yquake2/rogue/issues/122#issuecomment-1741844985

**Comment by NeonKnightOA** [comment]
I give my okay for both addons.

This is very good news for everybody.

**Comment by De-Seppe** [comment]
Ok for me

**Comment by Yamagi** [comment]
Hi,

we are currently in the process of relicensing the Yamagi Quake II addon libraries from the proprietary id Software SDK license to GPL2. This was made possible by id Software, which has included a GPL2 licensed copy of the unaltered addons source code into the Quake II Enhanced Edition SDK. See https://github.com/id-Software/quake2-rerelease-dll for details.

Since you have contributed at least one commit to the Yamagi Quake II The Reconing (xatrix) and / or Ground Zero (rogue) subprojects we need you okay to continue with the relicensing. Please give us a short notice either here or by mail to yamagi@yamagi.org if you are okay with the relicensing.

Thank you!

@afreuden 
@Dremor8484 
@Pickle 
@svdijk

**Comment by svdijk** [comment]
Ok from me for any code I've submitted to this repo!

**Comment by Pickle** [comment]
You have my permission to re-license my contributions

**Comment by Yamagi** [comment]
@afreuden and @Dremor8484, please give us you okay to license The Reckoning for Yamagi Quake II from the id Software SDK License to GPL2.

@afreuden has one commit, cec4adf2e4c0b96895e0fd32357c32ac02c03c22. It's a trivial change to the Makefile which translates to line 203 to 206 in the current git HEAD.

@Dremor8484 has several commits:
* 368df0875735b7541610b3c752cdb536e362c555 -> The same code is in yquake2.
* 44e50a12ca4cc3a10a32bb016df93aa1a77b800e -> Addition to the previous change, the same code is in yquake2.
* 04868b72ee80e0c51129267137cf93c65cff2e6c -> Applies the previous changes to the Phalanx. Not in yquake2, but just a copy and paste from the super shotgun change.

**Comment by Yamagi** [comment]
@Dremor8484, we need your okay to relicense The Reckoning from the id Software SDK license to GPL2.

**Comment by Yamagi** [comment]
The Reckoning / Xatrix is now GPL2 licensed.
